# Generated by Django 4.1.2 on 2023-04-16 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WorkoutApp', '0002_post_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='WorkoutApp.post'),
            preserve_default=False,
        ),
    ]
