# Generated by Django 4.1.2 on 2023-04-22 10:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('WorkoutApp', '0009_userprofile_banner_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='banner_pic',
            field=models.ImageField(blank=True, default='media/WorkoutApp/banners/yes4.jpg', null=True, upload_to='media/WorkoutApp/banners', verbose_name='banner pic'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='bio',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
